# Generated by Django 3.1 on 2020-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='default city', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='default image', max_length=1000),
        ),
    ]
