# Generated by Django 3.1 on 2020-08-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200805_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='display name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='default_image.jpg', max_length=1000),
        ),
    ]
